<p>
1. A partir de las matrices
$$
A = \begin{bmatrix}
1 & 3 & 3\\
2 & 4 & 1\\
\end{bmatrix}_{2\times3} \quad; B = \begin{bmatrix}
2 & 4 \\
1 & 5 \\
6 & 2 \\
\end{bmatrix}_{3\times2} 
$$
calcule AB, A'B'y BA
</p>

Solución:

In [24]:
#"pip install numpy": NumPy (Numerical Python) es una biblioteca de Python que se utiliza para trabajar con cálculos numéricos y operaciones matemáticas de manera eficiente. Su principal ventaja es que proporciona una estructura de datos llamada array (o matriz multidimensional), que permite realizar operaciones matemáticas y estadísticas rápidamente.

import numpy as np #importamos la libreia numpy
# Definimos las matrices A y B

A = np.array([[1, 3, 3],  # np.array: Crea una matriz a partir de una lista de listas  
              [2, 4, 1]])

B = np.array([[2, 4],     #cada vez que utilizamos np hacemos referencia a la libreria numpy
              [1, 5],                                                     
              [6, 2]])
# Calcular AB
AB = np.dot(A, B) #np.dot(A, B): Calcula el producto matricial de Ay B.
print("1) AB = \n", AB)      

# Calculamos las transpuestas de A y B
A_T = np.transpose(A)  # Transpuesta de A
B_T = np.transpose(B)  # Transpuesta de B

# Calcular el producto A'B'
AT_BT = np.dot(A_T, B_T)

print("2) Producto A'B' = \n", AT_BT)

BA = np.dot(B, A) #np.dot(A, B): Calcula el producto matricial de B y A.

print("3) BA = \n", BA)      



1) AB = 
 [[23 25]
 [14 30]]
2) Producto A'B' = 
 [[10 11 10]
 [22 23 26]
 [10  8 20]]
3) BA = 
 [[10 22 10]
 [11 23  8]
 [10 26 20]]
